title: CryptoDev.tv
author: Tomasz Kowalczyk
email: tkowalczyk.poczta@gmail.com
description: > 
  Cryptocurrencies from developer perspective.
  
twitter_username: tomkowalczyk
github_username: tkowalczyk
linkedin_username: kowalczykt
  
show_excerpts: false

theme: minima

header_pages:
  - about.md
